const {test}=require('node:test'), assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {transformSync}=require('esbuild');
const crypto=require('node:crypto');
const env={GOOGLE_CLIENT_ID:'fixture-client',GOOGLE_CLIENT_SECRET:'fixture-only',GOOGLE_REDIRECT_URI:'http://localhost:4000/auth/google/callback',FRONTEND_URL:'http://localhost:3000',JWT_SECRET:'fixture-only'};
function load(file,deps){const m={exports:{}};vm.runInNewContext(transformSync(fs.readFileSync(path.join(__dirname,'../src',file),'utf8'),{loader:'ts',format:'cjs'}).code,{module:m,exports:m.exports,require(n){if(n in deps)return deps[n];throw Error('Unexpected dependency '+n);},process:{env},URL,Date,console:{error(){throw Error('Logging prohibited');}}});return m.exports;}
const claims=()=>({iss:'https://accounts.google.com',aud:'fixture-client',sub:'google-user',nonce:'nonce',exp:Date.now()/1000+600,email:'Customer@Example.ca',email_verified:true,given_name:'Jean',family_name:'Test'});
let providerFailure=false;
const lib=load('lib/google-auth.ts',{crypto,'google-auth-library':{CodeChallengeMethod:{S256:'S256'},OAuth2Client:class{
 generateAuthUrl(q){return 'https://provider.invalid/?'+new URLSearchParams(q);}
 async getToken(q){assert.equal(q.codeVerifier,'verifier');assert.equal(q.redirect_uri,env.GOOGLE_REDIRECT_URI);if(providerFailure==='pkce')throw Error('PKCE failure');return {tokens:{id_token:'mock'}};}
 async verifyIdToken(q){assert.equal(q.idToken,'mock');assert.equal(q.audience,env.GOOGLE_CLIENT_ID);if(providerFailure==='signature')throw Error('signature');return {getPayload:claims};}
}}});
const res=()=>({statusCode:200,headers:{},set(){return this;},cookie(n,v){this.cookieValue=n+'='+v;return this;},clearCookie(){return this;},status(n){this.statusCode=n;return this;},json(v){this.data=v;return this;},redirect(v){this.url=v;return this;}});
function fixture({role='CLIENT',collision=false,providerError=false}={}){
 const records=[],users=[],identities=[];let reads=0,serial=Promise.resolve();
 const matches=(r,w)=>Object.entries(w).every(([k,v])=>v&&typeof v==='object'&&'gt'in v?r[k]>v.gt:r[k]===v);
 const db={googleAuthTransaction:{async create({data}){const r={id:String(records.length+1),authorizedAt:null,consumedAt:null,completedAt:null,...data};records.push(r);return {...r};},async findUnique({where}){const r=records.find(r=>matches(r,where));return r?{...r}:null;},async updateMany({where,data}){const r=records.find(r=>matches(r,where));if(!r)return {count:0};Object.assign(r,data);return {count:1};},async update({where,data}){Object.assign(records.find(r=>matches(r,where)),data);}},
 user:{async findUnique({where}){return users.find(u=>matches(u,where))||(collision?{id:'password-user',role,password:'hash'}:null);},async create({data}){if(users.some(u=>u.canonicalEmail===data.canonicalEmail))throw {code:'P2002'};const u={id:'u'+users.length,...data};users.push(u);identities.push({...data.externalIdentities.create,user:u});return u;}},
 externalIdentity:{async findUnique(){return identities[0]||null;}}};
 db.$transaction=(fn)=>{const result=serial.then(()=>fn(db));serial=result.catch(()=>{});return result;};
 const controller=load('controllers/google-auth.controller.ts',{'../lib/prisma':{prisma:db},'../lib/google-auth':{...lib,async readGoogleIdentity(){reads++;if(providerError)throw Error('provider');return {subject:'google-user',email:'Customer@Example.ca',firstName:'Jean',lastName:'Test'};}},jsonwebtoken:{sign(p){assert.equal(p.role,'CLIENT');return 'foodsave-jwt';}}});
 const request=(body)=>({body,get:()=>env.FRONTEND_URL,headers:{},query:{}});
 async function start(extra={}){const verifier=lib.randomSecret(),r=res();await controller.googleStart(request({challenge:lib.digest(verifier),locale:'en',...extra}),r);return {verifier,r};}
 async function ready(){const s=await start(),url=new URL(s.r.data.url),a=res();await controller.googleAuthorize({...request(),query:Object.fromEntries(url.searchParams)},a);return {...s,state:url.searchParams.get('state'),cookie:a.cookieValue};}
 async function callback(s,extra={}){const r=res();await controller.googleCallback({...request(),headers:{cookie:s.cookie},query:{state:s.state,code:'mock-code',...extra}},r);return r;}
 async function complete(s,r,verifier=s.verifier){const out=res();await controller.googleComplete(request({handoff:new URLSearchParams(new URL(r.url).hash.slice(1)).get('handoff'),verifier}),out);return out;}
 return {controller,db,records,users,identities,start,ready,callback,complete,request,get reads(){return reads;}};
}
test('new customer round trip, locale, JWT and one-time completion',async()=>{const f=fixture(),s=await f.ready(),r=await f.callback(s),out=await f.complete(s,r);assert.equal(out.data.token,'foodsave-jwt');assert.equal(out.data.locale,'en');assert.equal(f.users[0].role,'CLIENT');assert.equal(f.users[0].canonicalEmail,'customer@example.ca');assert.equal(f.users[0].password,null);assert.equal((await f.complete(s,r)).statusCode,400);assert.equal(f.records[0].pkceVerifier,'');});
test('returning identity retains user ID without creating another user',async()=>{const f=fixture();for(let i=0;i<2;i++){const s=await f.ready();assert.equal((await f.complete(s,await f.callback(s))).statusCode,200);}assert.equal(f.users.length,1);});
for(const role of ['CLIENT','MERCHANT','ADMIN'])test('existing canonical email collision never links '+role,async()=>{const f=fixture({collision:true,role}),s=await f.ready(),out=await f.complete(s,await f.callback(s));assert.equal(out.data.message,'auth.googleCollision');assert.equal(f.users.length,0);assert.equal(f.identities.length,0);});
for(const role of ['MERCHANT','ADMIN'])test('returning noncustomer blocked '+role,async()=>{const f=fixture(),s=await f.ready();await f.callback(s);f.users[0].role=role;const s2=await f.ready();assert.equal((await f.complete(s2,await f.callback(s2))).data.message,'auth.googleRole');assert.equal(f.users[0].role,role);});
test('role parameter rejected before transaction creation',async()=>{const f=fixture(),s=await f.start({role:'MERCHANT'});assert.equal(s.r.statusCode,400);assert.equal(f.records.length,0);});
test('concurrent callbacks consume exactly once',async()=>{const f=fixture(),s=await f.ready();const results=await Promise.all([f.callback(s),f.callback(s)]);assert.equal(results.filter(r=>r.url).length,1);assert.equal(f.reads,1);});
test('two concurrent new-account flows create one identity',async()=>{const f=fixture(),a=await f.ready(),b=await f.ready();await Promise.all([f.callback(a),f.callback(b)]);assert.equal(f.users.length,1);});
test('wrong browser callback and invalid state do not contact provider',async()=>{const f=fixture(),s=await f.ready();assert.equal((await f.callback({...s,cookie:''})).statusCode,400);assert.equal((await f.callback(s,{state:lib.randomSecret()})).statusCode,400);assert.equal(f.reads,0);});
test('expired transaction cannot reach provider',async()=>{const f=fixture(),s=await f.ready();f.records[0].expiresAt=new Date(0);assert.equal((await f.callback(s)).statusCode,400);assert.equal(f.reads,0);});
test('wrong handoff verifier cannot consume legitimate completion',async()=>{const f=fixture(),s=await f.ready(),r=await f.callback(s);assert.equal((await f.complete(s,r,lib.randomSecret())).statusCode,400);assert.equal((await f.complete(s,r)).statusCode,200);});
test('simultaneous completion issues exactly one JWT',async()=>{const f=fixture(),s=await f.ready(),r=await f.callback(s);const outcomes=await Promise.all([f.complete(s,r),f.complete(s,r)]);assert.equal(outcomes.filter(x=>x.statusCode===200).length,1);});
for(const [options,query,expected] of [[{providerError:true},{},'auth.googleUnavailable'],[{}, {error:'access_denied'},'auth.googleCancelled']])test('stable provider outcome '+expected,async()=>{const f=fixture(options),s=await f.ready(),r=await f.callback(s,query);assert.equal((await f.complete(s,r)).data.message,expected);assert.equal(f.users.length,0);});
test('unsafe origin and redirect override rejected',async()=>{const f=fixture(),r=res();await f.controller.googleStart({...f.request({challenge:lib.randomSecret(),locale:'fr'}),get:()=> 'https://evil.invalid'},r);assert.equal(r.statusCode,400);assert.equal((await f.start({redirect:'https://evil.invalid'})).r.statusCode,400);});
for(const patch of [{iss:'evil'},{aud:'evil'},{azp:'evil'},{nonce:'evil'},{exp:0},{sub:''},{email_verified:false},{email_verified:'true'},{email:null},{email:'bad email'}])test('claims rejected '+JSON.stringify(patch),()=>{assert.throws(()=>lib.validateGoogleClaims({...claims(),...patch},'nonce',env.GOOGLE_CLIENT_ID));});
test('valid claims canonical issuer accepted',()=>{assert.equal(lib.validateGoogleClaims(claims(),'nonce',env.GOOGLE_CLIENT_ID).subject,'google-user');});
for(const failure of ['pkce','signature'])test('library '+failure+' failure rejects without identity',async()=>{providerFailure=failure;try{await assert.rejects(lib.readGoogleIdentity('code','verifier','nonce'));}finally{providerFailure=false;}});
test('provider exchange sends PKCE verifier and validates token audience',async()=>{assert.equal((await lib.readGoogleIdentity('code','verifier','nonce')).subject,'google-user');});
test('authorization URL uses S256, nonce and minimal scopes',()=>{const url=new URL(lib.authorizationUrl('state','nonce','verifier'));assert.equal(url.searchParams.get('code_challenge'),lib.digest('verifier'));assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('nonce'),'nonce');});
